// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using uFrame.IOC;
using uFrame.Kernel;
using uFrame.MVVM;


public class ExampleSubSystemLoaderBase : uFrame.Kernel.SystemLoader {
    
    private EntityController _EntityController;
    
    [uFrame.IOC.InjectAttribute()]
    public virtual EntityController EntityController {
        get {
            if (_EntityController==null) {
                _EntityController = Container.CreateInstance(typeof(EntityController)) as EntityController;;
            }
            return _EntityController;
        }
        set {
            _EntityController = value;
        }
    }
    
    public override void Load() {
        Container.RegisterViewModelManager<EntityViewModel>(new ViewModelManager<EntityViewModel>());
        Container.RegisterController<EntityController>(EntityController);
    }
}
