// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using uFrame.IOC;
using uFrame.Kernel;
using uFrame.MVVM;
using uFrame.MVVM.Bindings;
using uFrame.Serialization;
using UnityEngine;
using UniRx;


public partial class EntityViewModelBase : uFrame.MVVM.ViewModel {
    
    private P<String> _NameProperty;
    
    private P<Vector3> _PositionProperty;
    
    private P<Int32> _HealthProperty;
    
    public EntityViewModelBase(uFrame.Kernel.IEventAggregator aggregator) : 
            base(aggregator) {
    }
    
    public virtual P<String> NameProperty {
        get {
            return _NameProperty;
        }
        set {
            _NameProperty = value;
        }
    }
    
    public virtual P<Vector3> PositionProperty {
        get {
            return _PositionProperty;
        }
        set {
            _PositionProperty = value;
        }
    }
    
    public virtual P<Int32> HealthProperty {
        get {
            return _HealthProperty;
        }
        set {
            _HealthProperty = value;
        }
    }
    
    public virtual String Name {
        get {
            return NameProperty.Value;
        }
        set {
            NameProperty.Value = value;
        }
    }
    
    public virtual Vector3 Position {
        get {
            return PositionProperty.Value;
        }
        set {
            PositionProperty.Value = value;
        }
    }
    
    public virtual Int32 Health {
        get {
            return HealthProperty.Value;
        }
        set {
            HealthProperty.Value = value;
        }
    }
    
    public override void Bind() {
        base.Bind();
        _NameProperty = new P<String>(this, "Name");
        _PositionProperty = new P<Vector3>(this, "Position");
        _HealthProperty = new P<Int32>(this, "Health");
    }
    
    public override void Read(ISerializerStream stream) {
        base.Read(stream);
        this.Position = stream.DeserializeVector3("Position");;
        this.Health = stream.DeserializeInt("Health");;
    }
    
    public override void Write(ISerializerStream stream) {
        base.Write(stream);
        stream.SerializeVector3("Position", this.Position);
        stream.SerializeInt("Health", this.Health);
    }
    
    protected override void FillCommands(System.Collections.Generic.List<uFrame.MVVM.ViewModelCommandInfo> list) {
        base.FillCommands(list);
    }
    
    protected override void FillProperties(System.Collections.Generic.List<uFrame.MVVM.ViewModelPropertyInfo> list) {
        base.FillProperties(list);
        // PropertiesChildItem
        list.Add(new ViewModelPropertyInfo(_NameProperty, false, false, false, false));
        // PropertiesChildItem
        list.Add(new ViewModelPropertyInfo(_PositionProperty, false, false, false, false));
        // PropertiesChildItem
        list.Add(new ViewModelPropertyInfo(_HealthProperty, false, false, false, false));
    }
}

public partial class EntityViewModel {
    
    public EntityViewModel(uFrame.Kernel.IEventAggregator aggregator) : 
            base(aggregator) {
    }
}
